app/creator/__init__.py
from flask import Blueprint

bp = Blueprint('creator', __name__)


from app.creator import routes

app/creator/routes.py
import random
from datetime import datetime

from flask import render_template, request, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy import text

from app.creator import bp
from app.models import db, User, Language, Song, Album, Genre, PlayListChildren, Rating, PlayLogs


@bp.route('/creator_studio')
@login_required
def home():
    all_songs = Song.query.filter_by(artist_id=current_user.id).all()
    albums = Album.query.filter_by(creator_id=current_user.id).all()
    with db.engine.begin() as conn:
        rating = conn.execute(text(
            "SELECT avg(rating) from ratings where song_id in (select id from song where artist_id={user_id}) ".format(
                user_id=current_user.id))).fetchall()
        plays = conn.execute(text(
            "SELECT count(id) from play_logs where song_id in (select id from song where artist_id={user_id}) ".format(
                user_id=current_user.id))).fetchall()
        average_rating = (rating[0][0])
        total_plays = (plays[0][0])
    return render_template('creator/creator-profile.html', all_songs=all_songs, albums=albums,
                           average_rating=average_rating, total_plays=total_plays)


@bp.route('/public-profile/<int:creator_id>', methods=['GET'])
@login_required
def profile(creator_id):
    user = User.query.get(creator_id)
    # return current_user.user_type
    with db.engine.begin() as conn:
        rating = conn.execute(text(
            "SELECT avg(rating) from ratings where song_id in (select id from song where artist_id={user_id}) ".format(
                user_id=user.id))).fetchall()
        plays = conn.execute(text(
            "SELECT count(id) from play_logs where song_id in (select id from song where artist_id={user_id}) ".format(
                user_id=user.id))).fetchall()
    average_rating = (rating[0][0])
    total_plays = (plays[0][0])
    return render_template('creator/public-profile.html', creator=user, average_rating=average_rating,
                           total_plays=total_plays)


@bp.route('/creator/add_song', methods=['GET'])
@login_required
def add_song():
    languages = Language.query.all()

    albums = Album.query.filter_by(creator_id=current_user.id).all()
    # return current_user.user_type
    return render_template('creator/create-song.html', albums=albums, languages=languages)


@bp.route('/edit-song/<int:song_id>', methods=['GET'])
@login_required
def edit_song(song_id):
    languages = Language.query.all()
    genres = Genre.query.all()
    albums = Album.query.filter_by(creator_id=current_user.id).all()
    song = Song.query.filter_by(artist_id=current_user.id, id=song_id).first()
    return render_template('creator/edit-song.html', song=song, languages=languages, genres=genres, albums=albums)


@bp.route('/update-song/<int:song_id>', methods=['POST'])
@login_required
def update_song(song_id):
    song = Song.query.filter_by(id=song_id).first()

    song.title = request.form.get('song_name')
    song.album_id = request.form.get('album_id')
    song.language_id = request.form.get('language_id')
    song.lyrics = request.form.get('lyrics')
    if request.form.get('release_date') != '':
        song.release_year = request.form.get('release_date')

    if 'file' in request.files and request.files['file'].filename != '':
        file = request.files['file']
        filename = request.form.get('song_name') + str(random.randint(100, 1000)) + file.filename
        file.save('app/storage/songs/' + filename)
        song.duration = request.form.get('duration')
        song.file_path = filename

    if 'thumbnail' in request.files and request.files['thumbnail'].filename != '':
        thumbnail = request.files['thumbnail']
        thumbnail_name = request.form.get('song_name') + str(random.randint(100, 1000)) + thumbnail.filename
        thumbnail.save('app/storage/thumbnails/song/' + thumbnail_name)
        song.thumbnail = thumbnail_name

    db.session.commit()
    return redirect(url_for('main.play_song', song_id=song_id))


@bp.route('/delete-song/<int:song_id>', methods=['GET'])
@login_required
def delete_song(song_id):
    try:
        Song.query.filter_by(id=song_id).delete()
        PlayListChildren.query.filter_by(song_id=song_id).delete()
        Rating.query.filter_by(song_id=song_id).delete()
        PlayLogs.query.filter_by(song_id=song_id).delete()
    except Exception as error:
        return str(error)
    finally:
        db.session.commit()
    return redirect(url_for('main.index'))


@bp.route('/creator/store_song', methods=['POST'])
@login_required
def store_song():
    song_title = request.form.get('song_name')
    album_id = request.form.get('album_id')
    language_id = request.form.get('language_id')
    lyrics = request.form.get('lyrics')
    file = request.files['file']
    thumbnail = request.files['thumbnail']
    html_date = request.form.get('release_date')
    duration = request.form.get('duration')

    if file.filename != '':
        filename = song_title + str(random.randint(100, 1000)) + file.filename
        file.save('app/storage/songs/' + filename)
    else:
        filename = ''

    if thumbnail.filename != '':
        thumbnail_name = song_title + str(random.randint(100, 1000)) + thumbnail.filename
        thumbnail.save('app/storage/thumbnails/song/' + thumbnail_name)
    else:
        thumbnail_name = ''
    if html_date != '':
        date_obj = datetime.strptime(html_date, '%Y-%m-%d')
    else:
        date_obj = datetime.utcnow()
    new_song = Song(title=song_title,
                    album_id=album_id,
                    lyrics=lyrics,
                    language_id=language_id,
                    is_active=True,
                    release_year=date_obj,
                    artist_id=current_user.id,
                    duration=duration,
                    file_path=filename,
                    thumbnail=thumbnail_name)

    db.session.add(new_song)
    db.session.commit()

    return redirect(url_for('creator.home'))


@bp.route('/creator/add_album', methods=['GET'])
@login_required
def add_album():
    # return current_user.user_type
    genres = Genre.query.all()
    return render_template('creator/create-album.html', genres=genres)


@bp.route('/creator/edit_album/<int:album_id>', methods=['GET'])
@login_required
def edit_album(album_id):
    genres = Genre.query.all()
    album = Album.query.filter_by(album_id=album_id).first()

    return render_template('creator/edit-album.html', album=album, genres=genres)


@bp.route('/creator/delete_album/<int:album_id>', methods=['GET'])
@login_required
def delete_album(album_id):
    album = Album.query.filter_by(album_id=album_id).delete()
    Song.query.filter_by(album_id=album_id).delete()
    db.session.commit()
    return redirect(url_for('creator.home'))


@bp.route('/creator/update_album/<int:album_id>', methods=['POST'])
@login_required
def update_album(album_id):
    album = Album.query.get(album_id)
    album.album_name = request.form.get('album_name')
    album.genre_id = request.form.get('genre_id')
    file = request.files['file']

    if file.filename != '':
        filename = album.album_name + str(random.randint(100, 1000)) + file.filename
        file.save('app/storage/thumbnails/album/' + filename)
        album.thumbnail = filename
    db.session.commit()

    return redirect(url_for('creator.home'))


@bp.route('/creator/store_album', methods=['POST'])
@login_required
def store_album():
    album_name = request.form.get('album_name')
    genre_id = request.form.get('genre_id')
    file = request.files['file']

    if file.filename != '':
        filename = album_name + str(random.randint(100, 1000)) + file.filename
        file.save('app/storage/thumbnails/album/' + filename)
    else:
        filename = ''

    new_album = Album(album_name=album_name, thumbnail=filename, creator_id=current_user.id, genre_id=genre_id,
                      is_active=True)
    db.session.add(new_album)
    db.session.commit()

    return redirect(url_for('creator.home'))


@bp.route('/become_creator')
@login_required
def become_creator():
    user = User.query.filter_by(id=current_user.id).first()
    user.user_type = 'crtr'
    user.api_token = random.randint(10000000,90000000)
    db.session.commit()
    return redirect(url_for('creator.home'))

app/templates/creator/create-album.html
{% extends "layout/base.html" %}

{% block title %} Home {% endblock %}

{% block content %}
    <div class="header w-full h-36 bg-no-repeat bg-cover bg-top hover:bg-blend-hard-light "
         style="background-image: url('{{ url_for('static',filename='img/bg-img4.jpg') }}');">
        <div class="container">
            <h1 class="text-3xl text-center text-white pt-5 font-bold">
                Create Album
            </h1>
        </div>
    </div>
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <h2 class="text-2xl font-bold mb-3">Add New Album</h2>
                <form action="{{ url_for('creator.store_album') }}" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="album_name">Album Name</label>
                        <input type="text" required name="album_name" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Genre</label>
                        <select name="genre_id" class="form-control" required>
                            <option value="">--select--</option>
                            {% for genre in genres %}
                                <option value="{{ genre.genre_id }}">{{ genre.genre_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="song_name">Album Thumbnail (square picture is recomended)</label>
                        <input type="file" name="file" class="form-control">
                    </div>
                    <button class="btn btn-primary">Create Album</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

app/templates/creator/create-song.html
{% extends "layout/base.html" %}

{% block title %} Home {% endblock %}

{% block content %}
<div class="header w-full h-36 bg-no-repeat bg-cover bg-top hover:bg-blend-hard-light "
    style="background-image: url('{{ url_for('static',filename='img/bg-img4.jpg') }}');">
    <div class="container">
        <h1 class="text-3xl text-center text-white pt-5 font-bold">
            Add New Song
        </h1>
    </div>
</div>
<div class="container mt-3">
    <form action="{{ url_for('creator.store_song') }}" method="post" enctype="multipart/form-data">
    <div class="row justify-content-center">
        <div class="col-lg-4">
            <h2 class="text-2xl font-bold mb-3">Add New Song</h2>
                <div class="form-group">
                    <label>Song Name</label>
                    <input type="text" name="song_name" class="form-control" required>
                </div>

                <div class="form-group">
                    <label>Release Year</label>
                    <input type="date" name="release_date" class="form-control" >
                </div>

                <div class="form-group">
                    <label>Album</label>
                    <select name="album_id" class="form-control" required>
                        <option value="">--select--</option>
                        {% for album in albums %}
                        <option value="{{album.album_id}}">{{album.album_name}}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label>Language</label>
                    <select name="language_id" class="form-control" required>
                        <option value="">--select--</option>
                        {% for language in languages %}
                        <option value="{{language.lang_id}}">{{language.lang_name}}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="file">MP3 File</label>
                    <input type="file" accept="audio/mp3" id="file" name="file" class="form-control">
                    <input type="hidden" name="duration" id="duration" value="">
                </div>

        
              
            </div>
            <div class="col-lg-4">
                <div class="form-group mt-5">
                    <label for="thumbnail">Song Thumbnail</label>
                    <input type="file" id="thumbnail" name="thumbnail" class="form-control" accept="image/*">
                </div>
                <div class="form-group ">
                    <label>Lyrics</label>
                    <textarea name="lyrics" class="form-control" placeholder="Lyrics" id="" rows="15" required></textarea>
                </div>
                <div class="text-right">
                    <button class="btn btn-primary ">Add Song</button>
                </div>
            </div> 
         
        </div>
  
    </form>

</div>
{% endblock %}

{% block scripts %}
<script>
    $("#file").change(()=>{
        const fileInput = event.target;
        
        if (fileInput.files.length > 0) {
            
            const audioFile = fileInput.files[0];
            const audio = new Audio();
            audio.src = URL.createObjectURL(audioFile);

            audio.addEventListener('loadedmetadata', function () {
                $("#duration").val(audio.duration);
            });
        }
    });
</script>

{% endblock %}

app/templates/creator/creator-profile.html
{% extends "layout/base.html" %}

{% block title %} Home {% endblock %}

{% block content %}
    <div class="header w-full h-36 bg-white bg-no-repeat bg-cover bg-top hover:bg-blend-hard-light transition-all delay-1000 "
         style="background-image: url('{{ url_for('static',filename='img/bg-img4.jpg') }}');">
        <div class="container">
            <h1 class="text-3xl text-center text-white pt-5 font-black ">
                {{ current_user.name }}, Welcome to Creator Studio
            </h1>
        </div>
    </div>
    <div class="container mt-3">
        {% if current_user.user_type!='crtr' %}
            <div class="alert alert-dark p-5" role="alert">
                <div>
                    <h1 class="text-4xl">Ooops..!!</h1>
                    {% if current_user.user_type == 'user' %}
                        <h2 class="text-xl mb-2">
                            You can't access creator studio unless you are a creator !
                        </h2>
                        Become a creator and upload musics and albums now. <br>
                        <a href="{{ url_for('creator.become_creator') }}" onclick="return confirm('Are you sure ?')"
                           class="btn btn-success decoration-none"><i class="bi bi-person-add  "></i> Register as
                            Creator</a>
                    {% else %}
                        You are an admin, so you can't add songs
                    {% endif %}
                </div>
            </div>
        {% elif not current_user.is_allowed_to_create %}
            <div class="alert alert-danger">
                <h1 class="text-xl">You can't add musics</h1>
                Your Profile is blacklisted
            </div>
        {% else %}
            <div class="p-5">
                <div class="row mb-4">
                    <div class="col-lg-3 border px-3 py-2 rounded">
                        <h3 class="text-lg font-medium">Total Songs Uploaded</h3>
                        <h2 class="text-2xl">{{ all_songs | length }}</h2>
                    </div>
                    <div class="col-lg-3 border px-3 py-2 rounded">
                        <h3 class="text-lg font-medium">Total Albums</h3>
                        <h2 class="text-2xl">{{ albums | length }}</h2>
                    </div>

                    <div class="col-lg-3 border px-3 py-2 rounded">
                        <h3 class="text-lg font-medium">Average song Ratings</h3>
                        <h2 class="text-2xl">{{ 0 if average_rating is none else average_rating | round(2) }} / 5</h2>
                    </div>

                    <div class="col-lg-3 border px-3 py-2 rounded">
                        <h3 class="text-lg font-medium">Total Plays</h3>
                        <h2 class="text-2xl">{{ total_plays }}</h2>
                    </div>
                </div>

                <div class="clearfix mb-2">
                    <div class="float-left">
                        <h3 class="text-xl mb-2">My Uploads</h3>
                    </div>
                    <div class="float-right">
                        <a href="{{ url_for('creator.add_song') }}" class="btn btn-primary"> <i class="bi bi-plus "></i>
                            Add New Song</a>

                    </div>
                </div>
                <table class="table table-bordered">
                    <thead class="table-light">
                    <tr>
                        <th>#</th>
                        <th>Song Name</th>
                        <th>Language</th>
                        <th>Genre</th>
                        <th>Album</th>
                        <th>Plays</th>
                        <th>Status</th>
                        <th>Avg. Rating</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for song in (all_songs) %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ song.title }}</td>
                            <td>{{ song.language.lang_name }}</td>
                            <td>{{ song.album.genre.genre_name }}</td>
                            <td>{{ song.album.album_name }}</td>
                            <td>{{ song.get_total_plays() }}</td>
                            <td>
                                {% if song.is_active %}
                                    <span class="badge badge-success">Active</span>
                                {% else %}
                                    <span class="badge badge-danger">Flagged</span>
                                {% endif %}
                            </td>
                            <td>{{ song.get_average_rating() }}</td>
                            <td>
                                <a href="{{ url_for('main.play_song',song_id=song.id) }}"
                                   class="btn btn-sm btn-success"><i
                                        class="bi bi-play "></i> Play Song</a>
                                <a href="{{ url_for('creator.edit_song',song_id=song.id) }}"
                                   class="btn btn-sm  btn-secondary"><i
                                        class="bi bi-pen "></i> Edit Song</a>
                                <a href="{{ url_for('creator.delete_song',song_id=song.id) }}"
                                   onclick="return confirm('Song will be deleted permanently, are you sure ?')"
                                   class="btn btn-sm btn-danger"><i class="bi bi-trash "></i> Delete Song</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <div class="clearfix mb-2">

                    <div class="float-left">
                        <h3 class="text-xl ">My Albums</h3>
                    </div>
                    <div class="float-right">
                        <a href="{{ url_for('creator.add_album') }}" class="btn btn-primary"> <i
                                class="bi bi-plus "></i> Create New Album</a>
                    </div>
                </div>


                <table class="table table-bordered">
                    <thead class="table-light">
                    <tr>
                        <th>#</th>
                        <th>Album</th>
                        <th>Genre</th>
                        <th>Total Songs</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for album in albums %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ album.album_name }}</td>
                            <td>{{ album.genre.genre_name }}</td>
                            <td>{{ album.songs | length }}</td>
                            <td>
                                <a href="{{ url_for('main.view_album',aid=album.album_id) }}"
                                   class="btn  btn-sm btn-success"><i
                                        class="bi bi-eye "></i> View Album</a>
                                <a href="{{ url_for('creator.edit_album',album_id=album.album_id) }}"
                                   class="btn  btn-sm btn-secondary"><i
                                        class="bi bi-pen "></i> Edit Album</a>
                                <a href="{{ url_for('creator.delete_album',album_id=album.album_id) }}"
                                   onclick="return confirm('Songs belongs to this album also be deleted, are you sure ?')"
                                   class="btn btn-sm btn-danger"><i class="bi bi-trash "></i> Delete Album</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div>
                    <div class="alert alert-secondary">
                        <h1>API Token</h1>
                        <code>{{ current_user.api_token }}</code>
                        <p>Include in Query Parameter of Request as <code>user_token</code></p>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>




{% endblock %}

app/templates/creator/edit-album.html
{% extends "layout/base.html" %}

{% block title %} Home {% endblock %}

{% block content %}
    <div class="header w-full h-36 bg-no-repeat bg-cover bg-top hover:bg-blend-hard-light "
         style="background-image: url('{{ url_for('static',filename='img/bg-img4.jpg') }}');">
        <div class="container">
            <h1 class="text-3xl text-center text-white pt-5 font-bold">
                Create Album
            </h1>
        </div>
    </div>
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <h2 class="text-2xl font-bold mb-3">Add New Album</h2>
                <form action="{{ url_for('creator.update_album',album_id=album.album_id) }}" method="post"
                      enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="album_name">Album Name</label>
                        <input type="text" required name="album_name" value="{{ album.album_name }}"
                               class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Genre</label>
                        <select name="genre_id" class="form-control" required>
                            <option value="">--select--</option>
                            {% for genre in genres %}
                                <option {{ 'selected' if album.genre_id==genre.genre_id }}
                                        value="{{ genre.genre_id }}">{{ genre.genre_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="song_name">Album Thumbnail (square picture is recomended)</label>
                        <input type="file" name="file" class="form-control">
                    </div>
                    <button class="btn btn-primary">Update Album</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

app/templates/creator/edit-song.html
{% extends "layout/base.html" %}

{% block title %} Home {% endblock %}

{% block content %}
    <div class="header w-full h-36 bg-no-repeat bg-cover bg-top hover:bg-blend-hard-light "
         style="background-image: url('{{ url_for('static',filename='img/bg-img4.jpg') }}');">
        <div class="container">
            <h1 class="text-3xl text-center text-white pt-5 font-bold">
                Add New Song
            </h1>
        </div>
    </div>
    <div class="container mt-3">
        <form action="{{ url_for('creator.update_song',song_id=song.id) }}" method="post" enctype="multipart/form-data">
            <div class="row justify-content-center">
                <div class="col-lg-4">
                    <h2 class="text-2xl font-bold mb-3">Edit {{ song.title }}</h2>
                    <div class="form-group">
                        <label>Song Name</label>
                        <input type="text" value="{{ song.title }}" required name="song_name" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Release Year</label>
                        <input type="date" value="{{ song.release_date }}" name="release_date" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Album</label>
                        <select name="album_id" class="form-control" required>
                            <option value="">--select--</option>
                            {% for album in albums %}
                                <option {{ 'selected' if song.album_id==album.album_id }}
                                        value="{{ album.album_id }}">{{ album.album_name }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Language</label>
                        <select name="language_id" class="form-control" required>
                            <option value="">--select--</option>
                            {% for language in languages %}
                                <option {{ 'selected' if song.language_id==language.lang_id }}
                                        value="{{ language.lang_id }}">{{ language.lang_name }}</option>
                            {% endfor %}
                        </select>
                    </div>


                    <div class="form-group">
                        <label for="file">MP3 File</label>
                        <input type="file" accept="audio/mp3" id="file" name="file" class="form-control">
                        <input type="hidden" name="duration" id="duration" value="">
                    </div>


                </div>
                <div class="col-lg-4">
                    <div class="form-group mt-5">
                        <label for="thumbnail">Song Thumbnail</label>
                        <input type="file" id="thumbnail" accept="image/*" name="thumbnail" class="form-control">
                    </div>
                    <div class="form-group mt-5">
                        <label>Lyrics</label>
                        <textarea name="lyrics" class="form-control" placeholder="Lyrics" id=""
                                  rows="19">{{ song.lyrics }}</textarea>
                    </div>
                    <div class="text-right">
                        <button class="btn btn-primary ">Update Song</button>
                    </div>
                </div>

            </div>

        </form>

    </div>
{% endblock %}